apiVersion: templates.gatekeeper.sh/v1beta1
kind: ConstraintTemplate
metadata:
  name: k8sallowedregistry
spec:
  crd:
    spec:
      names:
        kind: K8sAllowedRegistry
      validation:
        openAPIV3Schema:
          properties:
            prefixes:
              type: array
              items:
                type: string
  targets:
    - target: admission.k8s.gatekeeper.sh
      rego: |
        package k8sallowedregistry

        violation[{"msg": msg}] {
          container := input.review.object.spec.template.spec.containers[_]
          not startswith(container.image, allowed_prefixes[_])
          msg := sprintf("image %s is not from an allowed registry", [container.image])
        }

        allowed_prefixes[p] {
          p := input.parameters.prefixes[_]
        }
