bases:
  - ../../base
patchesStrategicMerge:
  - patches/gateway-service.yaml
  - patches/web-ingress.yaml
configMapGenerator:
  - name: env-overrides
    behavior: merge
    literals:
      - DEPLOYMENT_ENV=dev
images:
  - name: gateway
    newName: localhost:5001/gateway
    newTag: dev
  - name: users
    newName: localhost:5001/users
    newTag: dev
  - name: orders
    newName: localhost:5001/orders
    newTag: dev
  - name: inventory
    newName: localhost:5001/inventory
    newTag: dev
  - name: payments
    newName: localhost:5001/payments
    newTag: dev
  - name: notifications
    newName: localhost:5001/notifications
    newTag: dev
  - name: web
    newName: localhost:5001/web
    newTag: dev
