bases:
  - ../../base
configMapGenerator:
  - name: env-overrides
    behavior: merge
    literals:
      - DEPLOYMENT_ENV=prod
images:
  - name: gateway
    newName: ${ARTIFACT_REGISTRY}/gateway
    newTag: ${VERSION}
  - name: users
    newName: ${ARTIFACT_REGISTRY}/users
    newTag: ${VERSION}
  - name: orders
    newName: ${ARTIFACT_REGISTRY}/orders
    newTag: ${VERSION}
  - name: inventory
    newName: ${ARTIFACT_REGISTRY}/inventory
    newTag: ${VERSION}
  - name: payments
    newName: ${ARTIFACT_REGISTRY}/payments
    newTag: ${VERSION}
  - name: notifications
    newName: ${ARTIFACT_REGISTRY}/notifications
    newTag: ${VERSION}
  - name: web
    newName: ${ARTIFACT_REGISTRY}/web
    newTag: ${VERSION}
